# Copyright (c) 2024 CannonKeys LLC
# SPDX-License-Identifier: MIT

# Disable RGB underglow — the XIAO BLE dongle has no LEDs
CONFIG_ZMK_RGB_UNDERGLOW=n

# Disable ext-power (not present on the XIAO BLE)
CONFIG_ZMK_EXT_POWER=n

# Increase BT TX power for reliable connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
